default_stages: [commit]
repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
        -   id: jinja-ninja
            name: Jinja Validation
            language: system
            entry: bash -c 'poetry shell && jinja-ninja'
            files: ^app/
